package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/situmorangbastian/grip/graph/model"
)

// Examples is the resolver for the examples field.
func (r *queryResolver) Examples(ctx context.Context) ([]*model.Example, error) {
	return []*model.Example{
		{
			ID: "example-id",
		},
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
